- deskriptif : hanya menjabarkan data
- populasi : keseluruhan semua elemen
- outlier : melebihi batas kewajaran dari mayoritas sampel
- nan kalo diapa apain hasilnya ttp nan
- inferensial : kesimpulan data, prediksinya bagaimana
- populasi : keseluruhan dari elemen
- sampel : sebagian dari populasi
- range : nilai tertinggi - nilai terendah

# DESCRIPTIVE STATISTICS

In [ ]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [ ]:
math.nan

nan

In [ ]:
np.nan

nan

In [ ]:
x = [8,1,2.5,4,28]
x_with_nan = [8,1,2.5,np.nan,4,28]
print(x)
print(x_with_nan)

[8, 1, 2.5, 4, 28]
[8, 1, 2.5, nan, 4, 28]


In [ ]:
#membuat array(y) dan Series(z) dari x
y , y_with_nan = np.array(x), np.array(x_with_nan) #array
z , z_with_nan = pd.Series(x), pd.Series(x_with_nan) #series

print(y)
print(y_with_nan)
print(z)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [ ]:
z_with_nan.isna()

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

# CENTRAL TENDENCY

In [ ]:
x

[8, 1, 2.5, 4, 28]

In [ ]:
sum(x)

43.5

In [ ]:
len(x)

5

In [ ]:
# menghitung mean
mean_x = sum(x)/len(x)
mean_x

8.7

In [ ]:
# menghitung mean
mean_stats = statistics.mean(x)
print(mean_stats)

8.7


In [ ]:
# menghitung mean
mean_np = np.mean(x)
print(mean_np)

8.7


In [ ]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [ ]:
y.mean() #array

8.7

In [ ]:
z.mean() #series

8.7

In [ ]:
y_with_nan.mean()

nan

In [ ]:
np.mean(y_with_nan)

nan

In [ ]:
np.nan*3

nan

In [ ]:
#get mean without considering NaN values
np.nanmean(y_with_nan) 

8.7

In [ ]:
#kalo series langsung merata-ratakan nilai tanpa mempertimbangkan NaN values
z_with_nan.mean() 

8.7

In [ ]:
z_with_nan

0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64

# WEIGHTED MEAN
Rata-rata dengan menghitung pembobotan

In [ ]:
x = [8,1,2.5,4,28] #Metrics
w = [0.1,0.2,0.3,0.25,0.15] #Weightages

#menconvert jadi array
y,z,w = np.array(x),pd.Series(x),np.array(w)

wmean = np.average(y , weights=w)
print(wmean)

6.95


In [ ]:
#manual calculation
wmean_manual = sum(w[i]*x[i] for i in range(len(x)))/sum(w)
print(wmean)

6.95


In [ ]:
sum(w)

1.0

# HARMONIC MEAN

sering digunakan untuk rata-rata Rate (10km/jam,100kg/hari,1000000 orang/tahun)

In [ ]:
speed = [60,20]
hmean_speed = len(speed)/sum(1/item for item in speed)
hmean_speed

30.0

In [ ]:
# hmean dengan library 1
hmean_speed_stats = statistics.harmonic_mean(speed)
hmean_speed_stats

30.0

In [ ]:
# hmean dengan library 1
hmean_speed_stats2 = scipy.stats.hmean(speed)
hmean_speed_stats2

30.0

In [ ]:
x

[8, 1, 2.5, 4, 28]

In [ ]:
hmean = len(x) / sum(1/item for item in x)
hmean

2.7613412228796843

In [ ]:
arit_mean = np.mean(x)
arit_mean

8.7

In [ ]:
x

[8, 1, 2.5, 4, 28]

In [ ]:
for item in x:
    print(1/item)

0.125
1.0
0.4
0.25
0.03571428571428571


In [ ]:
list(1/item for item in x)

[0.125, 1.0, 0.4, 0.25, 0.03571428571428571]

In [ ]:
# hmean dgn library
hmean_stats = statistics.harmonic_mean(x)
hmean_stats

2.7613412228796843

# GEOMETRIC MEAN

Perusahaan berdiri pada tahun 2017

tahun 2017 omsetnya 1000

di tahun 2018 naik 30 %

di tahun 2019 naik 50 %

di tahun 2020 naik 40 %

In [ ]:
x = 1000
x*=1.3 #1300
x*=1.5 #1950
x*=1.4 #2730
x

2730.0

In [ ]:
# Arithmetic Mean
(30+50+40)/3

40.0

In [ ]:
x = 1000
x*=1.4
x*=1.4
x*=1.4
x

2743.9999999999995

In [ ]:
#Geometric Mean
gmean = ((30*50*40)**(1/3))
gmean

39.148676411688626

In [ ]:
x = 1000
x*=1.3915
x*=1.3915
x*=1.3915
x

2694.322835875

In [ ]:
#geometric mean menggunakan library scipy
scipy.stats.gmean([30,50,40])

39.14867641168864

# MEDIAN

In [ ]:
# jumlah angkanya ganjil
a = [1,2,4,8,9]
n = len(a)
median = a[2]
median

4

In [ ]:
#jumlah angkanya genap
a = [1,2,4,8]
n = len(a)
(n+1)/2
median = (2+4)/2
median

3.0

In [ ]:
# Menggunakan numpy
x = [8, 1, 2.5, 4, 28]
c = [2,3,4,5]
np.median(c)

3.5

In [ ]:
# Pembuktian manual
def median_function(x):
    n = len(x)
    if n%2 == 1: #Ganjil
        median_ = sorted(x)[round(0.5*(n-1))] #ambil median
    else: #Genap
        x_ord, index = sorted(x) , round(0.5*n)
        median_=0.5 * (x_ord[index-1]+x_ord[index])
    return median_

In [ ]:
median_function(x)

4

In [ ]:
median_function(c)

3.5

In [ ]:
# mengurutkan nilia terkecil sampai terbesar
sorted(x)

[1, 2.5, 4, 8, 28]

In [ ]:
n = len([1,2,3,4,5,6,7])
round(0.5*(n-1))

3

In [ ]:
n

7

# MODE/MODUS

Nilai yang paling sering banyak muncul/frekuensi paling tinggi

In [ ]:
u = [2,3,2,8,12]

mode_ = max((u.count(i),i)for i in set(u))[1]

In [ ]:
statistics.mode(u)

2

In [ ]:
scipy.stats.mode(u)[0][0]

<ipython-input-53-d8f8f9254a13>:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  scipy.stats.mode(u)[0][0]


2

In [ ]:
mode_lib = scipy.stats.mode(u)

<ipython-input-54-11d63c7822d9>:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_lib = scipy.stats.mode(u)


In [ ]:
print(mode_lib)
print(mode_lib.mode)
print(mode_lib.count)

ModeResult(mode=array([2]), count=array([2]))
[2]
[2]


In [ ]:
u

[2, 3, 2, 8, 12]

In [ ]:
u_series = pd.Series(u)
u_series.mode()

0    2
dtype: int64

In [ ]:
u_array = np.array(u)
statistics.mode(u_array)

2

In [ ]:
v = pd.Series([1,2,3,3,3,np.nan,np.nan,np.nan,np.nan])
v.mode()

0    3.0
dtype: float64

In [ ]:
statistics.mode(v)

3.0

In [ ]:
h = [1,2,3,3,3,np.nan,np.nan,np.nan,np.nan]
statistics.mode(h)

nan

In [ ]:
x

[8, 1, 2.5, 4, 28]

In [ ]:
n  = len(x)
mean_var = np.mean(x)
var_ = sum((item-mean_var)**2 for item in x ) / (n-1)
var_

123.19999999999999

# VARIANCE

In [ ]:
# Variance w/ statistics library
var_stat = statistics.variance(x)
var_stat

123.2

In [ ]:
# variance w/ numpy
var_np = np.var(x,ddof=1)
var_np

123.19999999999999

In [ ]:
# Variance using Series function
z = pd.Series(x)
z.var()

123.19999999999999

# QUIZ

 hitung variance dan standar deviasi

In [ ]:
x = [1,2,3,6,7,8,30,40,50]
std_dev = statistics.stdev(x)
print("Standar Deviasi dari x adalah:", std_dev)

variance = statistics.variance(x)
print("Variansi dari x adalah:", variance)

Standar Deviasi dari x adalah: 18.58090417606205
Variansi dari x adalah: 345.25000000000006


In [ ]:
x = [1,2,3,6,7,8,30,40,50]
n = len(x)
mean = sum(x)/n
var_ = sum((item - mean)**2 for item in x)/(n-1)
Sd_ = var_**(1/2) #

print(var_)
print(Sd_)

345.25000000000006
18.58090417606205


In [ ]:
x = [8, 1, 2.5, 4, 28]

In [ ]:
var_np

123.19999999999999

In [ ]:
stdev = var_np**(1/2)

In [ ]:
stdev

11.099549540409285

In [ ]:
stdev = np.sqrt(var_np) 
stdev

11.099549540409285

In [ ]:
# stdev with statistics library
stdev = statistics.stdev(x)
stdev

11.099549540409287

In [ ]:
stdev = np.std(x,ddof=1)
stdev

11.099549540409285

# SKEWNESS

In [ ]:
x

[8, 1, 2.5, 4, 28]

In [ ]:
n = len(x)
mean = np.mean(x)
stdev = statistics.stdev(x)
skew_ = (sum((item - mean)**3 for item in x))*n / ((n-1)*(n-2)*(stdev**3))
skew_

1.947043227390592

In [ ]:
scipy.stats.skew(x,bias=False)

1.9470432273905927

In [ ]:
z = pd.Series(x)
z.skew()

1.9470432273905924

In [ ]:
scipy.stats.skew(x_with_nan)

nan

In [ ]:
z_with_nan = pd.Series(x_with_nan)
z_with_nan.skew()

1.9470432273905924

In [ ]:
scipy.stats.skew(z_with_nan)

nan

# Percentiles

In [ ]:
x = [-5,-1.1,0.1,2,8,12.8,21,25.8,41]
np.percentile(x,5) #Percentile ke 5

-3.44

In [ ]:
np.percentile(x,0)

-5.0

In [ ]:
np.percentile(x,100)

41.0

In [ ]:
np.percentile(x,90)

28.840000000000003

In [ ]:
statistics.quantiles(x,n=2)

[8.0]

In [ ]:
statistics.quantiles(x,n=4)

[-0.5, 8.0, 23.4]

In [ ]:
statistics.quantiles(x,n=4,method='inclusive')

[0.1, 8.0, 21.0]

In [ ]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [ ]:
np.quantile(x,0)

-5.0

In [ ]:
np.quantile(x,1)

41.0

In [ ]:
np.quantile(x,0.5)

8.0

In [ ]:
x 

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [ ]:
x_with_nan = [-5, -1.1,np.nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]
x_with_nan

[-5, -1.1, nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [ ]:
np.quantile(x_with_nan,0)

nan

In [ ]:
np.nanquantile(x_with_nan,0.5)

8.0

In [ ]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [ ]:
np.quantile(x,[0.25,0.5,0.75])

array([ 0.1,  8. , 21. ])

In [ ]:
statistics.quantiles(x,n=4,method='inclusive')

[0.1, 8.0, 21.0]

In [ ]:
np.percentile(x,[25,50,75])

array([ 0.1,  8. , 21. ])

# RANGES (Nilai Max - Nilai Min)

In [ ]:
x # Ranges  = 41 - (-5) = 46

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [ ]:
# np.ptp untuk menghitung range
np.ptp(x)

46.0

In [ ]:
np.amax(x)

41.0

In [ ]:
np.amin(x)

-5.0

In [ ]:
np.amax(x) - np.amin(x)

46.0

# INTERQUANTILE RANGE (Q3-Q1) (biasanya digunakan untuk mendeteksi outlier)

In [ ]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [ ]:
quartiles = np.quantile(x,[0.25,0.75])
IQR = quartiles[1] - quartiles[0]
IQR

20.9

# Summary of Desc. Stats

In [ ]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [ ]:
result = scipy.stats.describe(x,ddof=1,bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [ ]:
(result.variance)**(1/2)

15.12454774346805

In [ ]:
result.minmax[1]-result.minmax[0]

46.0

In [ ]:
result.skewness

0.9249043136685094

In [ ]:
z = pd.Series(x)
z

0    -5.0
1    -1.1
2     0.1
3     2.0
4     8.0
5    12.8
6    21.0
7    25.8
8    41.0
dtype: float64

In [ ]:
z.describe()

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

# CORRELATION

In [ ]:
x = list(range(-10,11))
y = [0 , 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]
x_ar, y_ar = np.array(x),np.array(y)
x_s,y_s = pd.Series(x),pd.Series(y)

In [ ]:
len(x)==len(y)

True

# COVARIANCE

In [ ]:
n = len(x)
mean_x = np.mean(x)
mean_y = np.mean(y)

cov_xy = (sum((x[item]-mean_x)*(y[item]-mean_y) for item in range(n)))/(n-1)
cov_xy

19.95

In [ ]:
cov_matrix = np.cov(x,y)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [ ]:
np.var(x,ddof=1)

38.5

In [ ]:
np.var(y,ddof=1)

13.914285714285711

In [ ]:
cov_xy = cov_matrix[0,1]
cov_xy

19.95

In [ ]:
cov_xy = cov_matrix[1,0]
cov_xy

19.95

## Correlation Coefficient

r = 1 / r= -1 atau mendekati merupakan tanda kedua variabel mengalami multicollinearity

In [ ]:
# korelasi kuat karna mendekati 1
var_x = np.var(x,ddof=1)
var_y = np.var(y,ddof=1)
cov_xy
std_x = var_x**(1/2)
std_y = var_y**(1/2)
r = cov_xy / (std_x*std_y)
r

0.861950005631606

In [ ]:
r , p = scipy.stats.pearsonr(x,y)
r

0.8619500056316061

In [ ]:
p

5.122760847201132e-07